### ISSUE TITLE
Some question about perform bias+knob

### ISSUE THREAD

**Issue by DuCkBlAcK** [francozappa/bias#2]
Hi,
I am a newbie in Bluetooth security. Shall I ask some questions about bias and knob?
I read your paper which is super fantastic! And in the paper, you mentioned the bias is used to bypass the authentication, the knob is used to let the session key(used for encryption) simple after authentication bypassed. Is my understanding correct?

Back to this toolkit, in readme file you describe this step:
"Change lmin and lmax to set the max and min entropy value for the session key (KNOB attack)"
I have three questions:

1. Does this mean that if I set up lmin and lmax well, this toolkit will also help me to do the knob attack with bias together automotically?
2. How can I set lmin and lmax? I saw in configuration file, you set these two values to '07', do I need to change that? Or how can I set that to make session key more simple?
3. As stated in your paper, the knock attack is to make the session key simple and then brute force decrypt. Does this toolkit contain a brute force and decryption part scripts?

Many thanks,

Brian

**Comment by francozappa** [comment]
Hi Brian,

Thanks for your interest! Let me answer in line: 
1. Yes
2. Yes, e.g., If you set both to `01` then you will negotiate 1 Byte of entropy
3. No, you can look at my knob repository for the brute force part

**Comment by KamicDemon** [comment]
Hello, thanks for all the great work. I know this issue is closed, but I had a question that is sort of related.

Does this attack's success _require_ the target device to be susceptible to KNOB as well? I'm testing a device that was upgraded to resist KNOB, and I've confirmed that it does in fact reject KNOB attacks, but in my region the CYW920819 boards are completely out of stock.

Unless this PoC is somehow able to be used with other internalblue devices (I have a Nexus5 in my lab and a few Rpis) I don't think I'll be able to test for BIAS susceptibility. If BIAS does rely on KNOB to work then I'm hoping my device will be immune by extension.

Any information would be great, thank you.

**Comment by francozappa** [comment]
Hi Kamel,

No, the BIAS attack does not require susceptibility to KNOB, you can test the two attacks in isolation.
